//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.ServiceReferenceMatchNotification {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMatchNotification.IMatchNotificationService", CallbackContract=typeof(Hangman.Client.ServiceReferenceMatchNotification.IMatchNotificationServiceCallback))]
    public interface IMatchNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationService/Subscribe", ReplyAction="http://tempuri.org/IMatchNotificationService/SubscribeResponse")]
        Hangman.Contracts.Match.SubscribeMatchResponse Subscribe(Hangman.Contracts.Match.SubscribeMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationService/Subscribe", ReplyAction="http://tempuri.org/IMatchNotificationService/SubscribeResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.SubscribeMatchResponse> SubscribeAsync(Hangman.Contracts.Match.SubscribeMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationService/Unsubscribe", ReplyAction="http://tempuri.org/IMatchNotificationService/UnsubscribeResponse")]
        Hangman.Contracts.Match.UnsubscribeMatchResponse Unsubscribe(Hangman.Contracts.Match.UnsubscribeMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationService/Unsubscribe", ReplyAction="http://tempuri.org/IMatchNotificationService/UnsubscribeResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.UnsubscribeMatchResponse> UnsubscribeAsync(Hangman.Contracts.Match.UnsubscribeMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationService/SubscribeAvailableLobbies", ReplyAction="http://tempuri.org/IMatchNotificationService/SubscribeAvailableLobbiesResponse")]
        Hangman.Contracts.Match.SubscribeAvailableLobbiesResponse SubscribeAvailableLobbies(Hangman.Contracts.Match.SubscribeAvailableLobbiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationService/SubscribeAvailableLobbies", ReplyAction="http://tempuri.org/IMatchNotificationService/SubscribeAvailableLobbiesResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.SubscribeAvailableLobbiesResponse> SubscribeAvailableLobbiesAsync(Hangman.Contracts.Match.SubscribeAvailableLobbiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationService/UnsubscribeAvailableLobbies", ReplyAction="http://tempuri.org/IMatchNotificationService/UnsubscribeAvailableLobbiesResponse")]
        Hangman.Contracts.Match.UnsubscribeAvailableLobbiesResponse UnsubscribeAvailableLobbies(Hangman.Contracts.Match.UnsubscribeAvailableLobbiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationService/UnsubscribeAvailableLobbies", ReplyAction="http://tempuri.org/IMatchNotificationService/UnsubscribeAvailableLobbiesResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.UnsubscribeAvailableLobbiesResponse> UnsubscribeAvailableLobbiesAsync(Hangman.Contracts.Match.UnsubscribeAvailableLobbiesRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchNotificationServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchNotificationService/OnLobbyUpdated")]
        void OnLobbyUpdated(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchNotificationService/OnLobbyClosed")]
        void OnLobbyClosed(int matchId, string messageCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchNotificationService/OnMatchStatusChanged")]
        void OnMatchStatusChanged(int matchId, string matchStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchNotificationService/OnAvailableLobbiesChanged")]
        void OnAvailableLobbiesChanged();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchNotificationServiceChannel : Hangman.Client.ServiceReferenceMatchNotification.IMatchNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchNotificationServiceClient : System.ServiceModel.DuplexClientBase<Hangman.Client.ServiceReferenceMatchNotification.IMatchNotificationService>, Hangman.Client.ServiceReferenceMatchNotification.IMatchNotificationService {
        
        public MatchNotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchNotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchNotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchNotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchNotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Hangman.Contracts.Match.SubscribeMatchResponse Subscribe(Hangman.Contracts.Match.SubscribeMatchRequest request) {
            return base.Channel.Subscribe(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.SubscribeMatchResponse> SubscribeAsync(Hangman.Contracts.Match.SubscribeMatchRequest request) {
            return base.Channel.SubscribeAsync(request);
        }
        
        public Hangman.Contracts.Match.UnsubscribeMatchResponse Unsubscribe(Hangman.Contracts.Match.UnsubscribeMatchRequest request) {
            return base.Channel.Unsubscribe(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.UnsubscribeMatchResponse> UnsubscribeAsync(Hangman.Contracts.Match.UnsubscribeMatchRequest request) {
            return base.Channel.UnsubscribeAsync(request);
        }
        
        public Hangman.Contracts.Match.SubscribeAvailableLobbiesResponse SubscribeAvailableLobbies(Hangman.Contracts.Match.SubscribeAvailableLobbiesRequest request) {
            return base.Channel.SubscribeAvailableLobbies(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.SubscribeAvailableLobbiesResponse> SubscribeAvailableLobbiesAsync(Hangman.Contracts.Match.SubscribeAvailableLobbiesRequest request) {
            return base.Channel.SubscribeAvailableLobbiesAsync(request);
        }
        
        public Hangman.Contracts.Match.UnsubscribeAvailableLobbiesResponse UnsubscribeAvailableLobbies(Hangman.Contracts.Match.UnsubscribeAvailableLobbiesRequest request) {
            return base.Channel.UnsubscribeAvailableLobbies(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.UnsubscribeAvailableLobbiesResponse> UnsubscribeAvailableLobbiesAsync(Hangman.Contracts.Match.UnsubscribeAvailableLobbiesRequest request) {
            return base.Channel.UnsubscribeAvailableLobbiesAsync(request);
        }
    }
}
