//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.ServiceReferenceMatchGameplay {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMatchGameplay.IMatchGameplayService")]
    public interface IMatchGameplayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/VoteCategory", ReplyAction="http://tempuri.org/IMatchGameplayService/VoteCategoryResponse")]
        Hangman.Contracts.Match.VoteCategoryResponse VoteCategory(Hangman.Contracts.Match.VoteCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/VoteCategory", ReplyAction="http://tempuri.org/IMatchGameplayService/VoteCategoryResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.VoteCategoryResponse> VoteCategoryAsync(Hangman.Contracts.Match.VoteCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/GetCategoryVotingState", ReplyAction="http://tempuri.org/IMatchGameplayService/GetCategoryVotingStateResponse")]
        Hangman.Contracts.Match.GetCategoryVotingStateResponse GetCategoryVotingState(Hangman.Contracts.Match.GetCategoryVotingStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/GetCategoryVotingState", ReplyAction="http://tempuri.org/IMatchGameplayService/GetCategoryVotingStateResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.GetCategoryVotingStateResponse> GetCategoryVotingStateAsync(Hangman.Contracts.Match.GetCategoryVotingStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/ResolveCategoryVoting", ReplyAction="http://tempuri.org/IMatchGameplayService/ResolveCategoryVotingResponse")]
        Hangman.Contracts.Match.ResolveCategoryVotingResponse ResolveCategoryVoting(Hangman.Contracts.Match.ResolveCategoryVotingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/ResolveCategoryVoting", ReplyAction="http://tempuri.org/IMatchGameplayService/ResolveCategoryVotingResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.ResolveCategoryVotingResponse> ResolveCategoryVotingAsync(Hangman.Contracts.Match.ResolveCategoryVotingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/GetSelectableWords", ReplyAction="http://tempuri.org/IMatchGameplayService/GetSelectableWordsResponse")]
        Hangman.Contracts.Match.GetSelectableWordsResponse GetSelectableWords(Hangman.Contracts.Match.GetSelectableWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/GetSelectableWords", ReplyAction="http://tempuri.org/IMatchGameplayService/GetSelectableWordsResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.GetSelectableWordsResponse> GetSelectableWordsAsync(Hangman.Contracts.Match.GetSelectableWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/SelectWord", ReplyAction="http://tempuri.org/IMatchGameplayService/SelectWordResponse")]
        Hangman.Contracts.Match.SelectWordResponse SelectWord(Hangman.Contracts.Match.SelectWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayService/SelectWord", ReplyAction="http://tempuri.org/IMatchGameplayService/SelectWordResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.SelectWordResponse> SelectWordAsync(Hangman.Contracts.Match.SelectWordRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchGameplayServiceChannel : Hangman.Client.ServiceReferenceMatchGameplay.IMatchGameplayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchGameplayServiceClient : System.ServiceModel.ClientBase<Hangman.Client.ServiceReferenceMatchGameplay.IMatchGameplayService>, Hangman.Client.ServiceReferenceMatchGameplay.IMatchGameplayService {
        
        public MatchGameplayServiceClient() {
        }
        
        public MatchGameplayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchGameplayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchGameplayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchGameplayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hangman.Contracts.Match.VoteCategoryResponse VoteCategory(Hangman.Contracts.Match.VoteCategoryRequest request) {
            return base.Channel.VoteCategory(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.VoteCategoryResponse> VoteCategoryAsync(Hangman.Contracts.Match.VoteCategoryRequest request) {
            return base.Channel.VoteCategoryAsync(request);
        }
        
        public Hangman.Contracts.Match.GetCategoryVotingStateResponse GetCategoryVotingState(Hangman.Contracts.Match.GetCategoryVotingStateRequest request) {
            return base.Channel.GetCategoryVotingState(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.GetCategoryVotingStateResponse> GetCategoryVotingStateAsync(Hangman.Contracts.Match.GetCategoryVotingStateRequest request) {
            return base.Channel.GetCategoryVotingStateAsync(request);
        }
        
        public Hangman.Contracts.Match.ResolveCategoryVotingResponse ResolveCategoryVoting(Hangman.Contracts.Match.ResolveCategoryVotingRequest request) {
            return base.Channel.ResolveCategoryVoting(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.ResolveCategoryVotingResponse> ResolveCategoryVotingAsync(Hangman.Contracts.Match.ResolveCategoryVotingRequest request) {
            return base.Channel.ResolveCategoryVotingAsync(request);
        }
        
        public Hangman.Contracts.Match.GetSelectableWordsResponse GetSelectableWords(Hangman.Contracts.Match.GetSelectableWordsRequest request) {
            return base.Channel.GetSelectableWords(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.GetSelectableWordsResponse> GetSelectableWordsAsync(Hangman.Contracts.Match.GetSelectableWordsRequest request) {
            return base.Channel.GetSelectableWordsAsync(request);
        }
        
        public Hangman.Contracts.Match.SelectWordResponse SelectWord(Hangman.Contracts.Match.SelectWordRequest request) {
            return base.Channel.SelectWord(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.SelectWordResponse> SelectWordAsync(Hangman.Contracts.Match.SelectWordRequest request) {
            return base.Channel.SelectWordAsync(request);
        }
    }
}
