//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.ServiceReferenceAuth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAuth.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        Hangman.Contracts.Auth.RegisterResponse Register(Hangman.Contracts.Auth.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Auth.RegisterResponse> RegisterAsync(Hangman.Contracts.Auth.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Login", ReplyAction="http://tempuri.org/IAuthService/LoginResponse")]
        Hangman.Contracts.Auth.LoginResponse Login(Hangman.Contracts.Auth.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Login", ReplyAction="http://tempuri.org/IAuthService/LoginResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Auth.LoginResponse> LoginAsync(Hangman.Contracts.Auth.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/VerifyEmail", ReplyAction="http://tempuri.org/IAuthService/VerifyEmailResponse")]
        Hangman.Contracts.Auth.VerifyEmailResponse VerifyEmail(Hangman.Contracts.Auth.VerifyEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/VerifyEmail", ReplyAction="http://tempuri.org/IAuthService/VerifyEmailResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Auth.VerifyEmailResponse> VerifyEmailAsync(Hangman.Contracts.Auth.VerifyEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/ResendVerificationEmail", ReplyAction="http://tempuri.org/IAuthService/ResendVerificationEmailResponse")]
        Hangman.Contracts.Auth.ResendVerificationEmailResponse ResendVerificationEmail(Hangman.Contracts.Auth.ResendVerificationEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/ResendVerificationEmail", ReplyAction="http://tempuri.org/IAuthService/ResendVerificationEmailResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Auth.ResendVerificationEmailResponse> ResendVerificationEmailAsync(Hangman.Contracts.Auth.ResendVerificationEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/RequestPasswordReset", ReplyAction="http://tempuri.org/IAuthService/RequestPasswordResetResponse")]
        Hangman.Contracts.Auth.RequestPasswordResetResponse RequestPasswordReset(Hangman.Contracts.Auth.RequestPasswordResetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/RequestPasswordReset", ReplyAction="http://tempuri.org/IAuthService/RequestPasswordResetResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Auth.RequestPasswordResetResponse> RequestPasswordResetAsync(Hangman.Contracts.Auth.RequestPasswordResetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/ResetPassword", ReplyAction="http://tempuri.org/IAuthService/ResetPasswordResponse")]
        Hangman.Contracts.Auth.ResetPasswordResponse ResetPassword(Hangman.Contracts.Auth.ResetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/ResetPassword", ReplyAction="http://tempuri.org/IAuthService/ResetPasswordResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Auth.ResetPasswordResponse> ResetPasswordAsync(Hangman.Contracts.Auth.ResetPasswordRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : Hangman.Client.ServiceReferenceAuth.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<Hangman.Client.ServiceReferenceAuth.IAuthService>, Hangman.Client.ServiceReferenceAuth.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hangman.Contracts.Auth.RegisterResponse Register(Hangman.Contracts.Auth.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Auth.RegisterResponse> RegisterAsync(Hangman.Contracts.Auth.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public Hangman.Contracts.Auth.LoginResponse Login(Hangman.Contracts.Auth.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Auth.LoginResponse> LoginAsync(Hangman.Contracts.Auth.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public Hangman.Contracts.Auth.VerifyEmailResponse VerifyEmail(Hangman.Contracts.Auth.VerifyEmailRequest request) {
            return base.Channel.VerifyEmail(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Auth.VerifyEmailResponse> VerifyEmailAsync(Hangman.Contracts.Auth.VerifyEmailRequest request) {
            return base.Channel.VerifyEmailAsync(request);
        }
        
        public Hangman.Contracts.Auth.ResendVerificationEmailResponse ResendVerificationEmail(Hangman.Contracts.Auth.ResendVerificationEmailRequest request) {
            return base.Channel.ResendVerificationEmail(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Auth.ResendVerificationEmailResponse> ResendVerificationEmailAsync(Hangman.Contracts.Auth.ResendVerificationEmailRequest request) {
            return base.Channel.ResendVerificationEmailAsync(request);
        }
        
        public Hangman.Contracts.Auth.RequestPasswordResetResponse RequestPasswordReset(Hangman.Contracts.Auth.RequestPasswordResetRequest request) {
            return base.Channel.RequestPasswordReset(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Auth.RequestPasswordResetResponse> RequestPasswordResetAsync(Hangman.Contracts.Auth.RequestPasswordResetRequest request) {
            return base.Channel.RequestPasswordResetAsync(request);
        }
        
        public Hangman.Contracts.Auth.ResetPasswordResponse ResetPassword(Hangman.Contracts.Auth.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Auth.ResetPasswordResponse> ResetPasswordAsync(Hangman.Contracts.Auth.ResetPasswordRequest request) {
            return base.Channel.ResetPasswordAsync(request);
        }
    }
}
