//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.ServiceReferenceMatch {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMatch.IMatchService")]
    public interface IMatchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/CreateLobby", ReplyAction="http://tempuri.org/IMatchService/CreateLobbyResponse")]
        Hangman.Contracts.Match.CreateLobbyResponse CreateLobby(Hangman.Contracts.Match.CreateLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/CreateLobby", ReplyAction="http://tempuri.org/IMatchService/CreateLobbyResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.CreateLobbyResponse> CreateLobbyAsync(Hangman.Contracts.Match.CreateLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetAvailableLobbies", ReplyAction="http://tempuri.org/IMatchService/GetAvailableLobbiesResponse")]
        Hangman.Contracts.Match.GetAvailableLobbiesResponse GetAvailableLobbies(Hangman.Contracts.Match.GetAvailableLobbiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetAvailableLobbies", ReplyAction="http://tempuri.org/IMatchService/GetAvailableLobbiesResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.GetAvailableLobbiesResponse> GetAvailableLobbiesAsync(Hangman.Contracts.Match.GetAvailableLobbiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/JoinLobby", ReplyAction="http://tempuri.org/IMatchService/JoinLobbyResponse")]
        Hangman.Contracts.Match.JoinLobbyResponse JoinLobby(Hangman.Contracts.Match.JoinLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/JoinLobby", ReplyAction="http://tempuri.org/IMatchService/JoinLobbyResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.JoinLobbyResponse> JoinLobbyAsync(Hangman.Contracts.Match.JoinLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetCurrentLobby", ReplyAction="http://tempuri.org/IMatchService/GetCurrentLobbyResponse")]
        Hangman.Contracts.Match.GetCurrentLobbyResponse GetCurrentLobby(Hangman.Contracts.Match.GetCurrentLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetCurrentLobby", ReplyAction="http://tempuri.org/IMatchService/GetCurrentLobbyResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.GetCurrentLobbyResponse> GetCurrentLobbyAsync(Hangman.Contracts.Match.GetCurrentLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/LeaveLobby", ReplyAction="http://tempuri.org/IMatchService/LeaveLobbyResponse")]
        Hangman.Contracts.Match.LeaveLobbyResponse LeaveLobby(Hangman.Contracts.Match.LeaveLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/LeaveLobby", ReplyAction="http://tempuri.org/IMatchService/LeaveLobbyResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.LeaveLobbyResponse> LeaveLobbyAsync(Hangman.Contracts.Match.LeaveLobbyRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceChannel : Hangman.Client.ServiceReferenceMatch.IMatchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchServiceClient : System.ServiceModel.ClientBase<Hangman.Client.ServiceReferenceMatch.IMatchService>, Hangman.Client.ServiceReferenceMatch.IMatchService {
        
        public MatchServiceClient() {
        }
        
        public MatchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hangman.Contracts.Match.CreateLobbyResponse CreateLobby(Hangman.Contracts.Match.CreateLobbyRequest request) {
            return base.Channel.CreateLobby(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.CreateLobbyResponse> CreateLobbyAsync(Hangman.Contracts.Match.CreateLobbyRequest request) {
            return base.Channel.CreateLobbyAsync(request);
        }
        
        public Hangman.Contracts.Match.GetAvailableLobbiesResponse GetAvailableLobbies(Hangman.Contracts.Match.GetAvailableLobbiesRequest request) {
            return base.Channel.GetAvailableLobbies(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.GetAvailableLobbiesResponse> GetAvailableLobbiesAsync(Hangman.Contracts.Match.GetAvailableLobbiesRequest request) {
            return base.Channel.GetAvailableLobbiesAsync(request);
        }
        
        public Hangman.Contracts.Match.JoinLobbyResponse JoinLobby(Hangman.Contracts.Match.JoinLobbyRequest request) {
            return base.Channel.JoinLobby(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.JoinLobbyResponse> JoinLobbyAsync(Hangman.Contracts.Match.JoinLobbyRequest request) {
            return base.Channel.JoinLobbyAsync(request);
        }
        
        public Hangman.Contracts.Match.GetCurrentLobbyResponse GetCurrentLobby(Hangman.Contracts.Match.GetCurrentLobbyRequest request) {
            return base.Channel.GetCurrentLobby(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.GetCurrentLobbyResponse> GetCurrentLobbyAsync(Hangman.Contracts.Match.GetCurrentLobbyRequest request) {
            return base.Channel.GetCurrentLobbyAsync(request);
        }
        
        public Hangman.Contracts.Match.LeaveLobbyResponse LeaveLobby(Hangman.Contracts.Match.LeaveLobbyRequest request) {
            return base.Channel.LeaveLobby(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.LeaveLobbyResponse> LeaveLobbyAsync(Hangman.Contracts.Match.LeaveLobbyRequest request) {
            return base.Channel.LeaveLobbyAsync(request);
        }
    }
}
