//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.ServiceReferenceScore {


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceScore.IScoreService")]
    public interface IScoreService {

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScoreService/GetPlayerScore", ReplyAction="http://tempuri.org/IScoreService/GetPlayerScoreResponse")]
        Hangman.Contracts.Match.GetPlayerScoreResponse GetPlayerScore(Hangman.Contracts.Match.GetPlayerScoreRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScoreService/GetPlayerScore", ReplyAction="http://tempuri.org/IScoreService/GetPlayerScoreResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.GetPlayerScoreResponse> GetPlayerScoreAsync(Hangman.Contracts.Match.GetPlayerScoreRequest request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScoreServiceChannel : Hangman.Client.ServiceReferenceScore.IScoreService, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScoreServiceClient : System.ServiceModel.ClientBase<Hangman.Client.ServiceReferenceScore.IScoreService>, Hangman.Client.ServiceReferenceScore.IScoreService {

        public ScoreServiceClient() {
        }

        public ScoreServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName) {
        }

        public ScoreServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public ScoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public ScoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress) {
        }

        public Hangman.Contracts.Match.GetPlayerScoreResponse GetPlayerScore(Hangman.Contracts.Match.GetPlayerScoreRequest request) {
            return base.Channel.GetPlayerScore(request);
        }

        public System.Threading.Tasks.Task<Hangman.Contracts.Match.GetPlayerScoreResponse> GetPlayerScoreAsync(Hangman.Contracts.Match.GetPlayerScoreRequest request) {
            return base.Channel.GetPlayerScoreAsync(request);
        }
    }
}
