//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangman.Client.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        internal static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOGIN.
        /// </summary>
        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        internal static string Login_CreateAccount {
            get {
                return ResourceManager.GetString("Login_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Login_EmailLabel {
            get {
                return ResourceManager.GetString("Login_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Login_PasswordLabel {
            get {
                return ResourceManager.GetString("Login_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string Login_SettingsTooltip {
            get {
                return ResourceManager.GetString("Login_SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings are not available yet..
        /// </summary>
        internal static string Login_SettingsUnavailableMessage {
            get {
                return ResourceManager.GetString("Login_SettingsUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string Login_SettingsUnavailableTitle {
            get {
                return ResourceManager.GetString("Login_SettingsUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show password.
        /// </summary>
        internal static string Login_ShowPassword {
            get {
                return ResourceManager.GetString("Login_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hangman - Login.
        /// </summary>
        internal static string Login_WindowTitle {
            get {
                return ResourceManager.GetString("Login_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an account?.
        /// </summary>
        internal static string Register_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("Register_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGISTER.
        /// </summary>
        internal static string Register_Button {
            get {
                return ResourceManager.GetString("Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        internal static string Register_ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("Register_ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth.
        /// </summary>
        internal static string Register_DateOfBirthLabel {
            get {
                return ResourceManager.GetString("Register_DateOfBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Register_EmailLabel {
            get {
                return ResourceManager.GetString("Register_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a email@domain.com.
        /// </summary>
        internal static string Register_EmailTooltip {
            get {
                return ResourceManager.GetString("Register_EmailTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full name.
        /// </summary>
        internal static string Register_FullNameLabel {
            get {
                return ResourceManager.GetString("Register_FullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example: John Smith.
        /// </summary>
        internal static string Register_FullNameTooltip {
            get {
                return ResourceManager.GetString("Register_FullNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        internal static string Register_LoginLink {
            get {
                return ResourceManager.GetString("Register_LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Register_PasswordLabel {
            get {
                return ResourceManager.GetString("Register_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string Register_PhoneLabel {
            get {
                return ResourceManager.GetString("Register_PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example: 222-123-4567.
        /// </summary>
        internal static string Register_PhoneTooltip {
            get {
                return ResourceManager.GetString("Register_PhoneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferred language.
        /// </summary>
        internal static string Register_PreferredLanguageLabel {
            get {
                return ResourceManager.GetString("Register_PreferredLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEW PLAYER.
        /// </summary>
        internal static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hangman - Register.
        /// </summary>
        internal static string Register_WindowTitle {
            get {
                return ResourceManager.GetString("Register_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account is already verified..
        /// </summary>
        internal static string Server_Auth_AccountAlreadyVerified {
            get {
                return ResourceManager.GetString("Server_Auth_AccountAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account is not active..
        /// </summary>
        internal static string Server_Auth_AccountNotActive {
            get {
                return ResourceManager.GetString("Server_Auth_AccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account is not available..
        /// </summary>
        internal static string Server_Auth_AccountNotAvailable {
            get {
                return ResourceManager.GetString("Server_Auth_AccountNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account created successfully. Check your email to verify it..
        /// </summary>
        internal static string Server_Auth_AccountRegisteredEmailVerificationRequired {
            get {
                return ResourceManager.GetString("Server_Auth_AccountRegisteredEmailVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account created successfully, but the verification email could not be sent..
        /// </summary>
        internal static string Server_Auth_AccountRegisteredVerificationEmailNotSent {
            get {
                return ResourceManager.GetString("Server_Auth_AccountRegisteredVerificationEmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is already registered..
        /// </summary>
        internal static string Server_Auth_EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("Server_Auth_EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email verification data is required..
        /// </summary>
        internal static string Server_Auth_EmailVerificationDataRequired {
            get {
                return ResourceManager.GetString("Server_Auth_EmailVerificationDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account could not be verified..
        /// </summary>
        internal static string Server_Auth_EmailVerificationFailed {
            get {
                return ResourceManager.GetString("Server_Auth_EmailVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must verify your email before continuing..
        /// </summary>
        internal static string Server_Auth_EmailVerificationRequired {
            get {
                return ResourceManager.GetString("Server_Auth_EmailVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account was verified successfully..
        /// </summary>
        internal static string Server_Auth_EmailVerificationSuccessful {
            get {
                return ResourceManager.GetString("Server_Auth_EmailVerificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum number of verification attempts was exceeded..
        /// </summary>
        internal static string Server_Auth_EmailVerificationTokenAttemptsExceeded {
            get {
                return ResourceManager.GetString("Server_Auth_EmailVerificationTokenAttemptsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code has expired..
        /// </summary>
        internal static string Server_Auth_EmailVerificationTokenExpired {
            get {
                return ResourceManager.GetString("Server_Auth_EmailVerificationTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No valid verification code was found..
        /// </summary>
        internal static string Server_Auth_EmailVerificationTokenNotFound {
            get {
                return ResourceManager.GetString("Server_Auth_EmailVerificationTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full name is required..
        /// </summary>
        internal static string Server_Auth_FullNameRequired {
            get {
                return ResourceManager.GetString("Server_Auth_FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth is not valid..
        /// </summary>
        internal static string Server_Auth_InvalidDateOfBirth {
            get {
                return ResourceManager.GetString("Server_Auth_InvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is not valid..
        /// </summary>
        internal static string Server_Auth_InvalidEmail {
            get {
                return ResourceManager.GetString("Server_Auth_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email or password is incorrect..
        /// </summary>
        internal static string Server_Auth_InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("Server_Auth_InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code is not valid..
        /// </summary>
        internal static string Server_Auth_InvalidEmailVerificationCode {
            get {
                return ResourceManager.GetString("Server_Auth_InvalidEmailVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The recovery code is not valid..
        /// </summary>
        internal static string Server_Auth_InvalidPasswordResetCode {
            get {
                return ResourceManager.GetString("Server_Auth_InvalidPasswordResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected language is not valid..
        /// </summary>
        internal static string Server_Auth_InvalidPreferredLanguage {
            get {
                return ResourceManager.GetString("Server_Auth_InvalidPreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login data is required..
        /// </summary>
        internal static string Server_Auth_LoginDataRequired {
            get {
                return ResourceManager.GetString("Server_Auth_LoginDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login successful..
        /// </summary>
        internal static string Server_Auth_LoginSuccessful {
            get {
                return ResourceManager.GetString("Server_Auth_LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must not contain spaces..
        /// </summary>
        internal static string Server_Auth_PasswordContainsWhiteSpace {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordContainsWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required..
        /// </summary>
        internal static string Server_Auth_PasswordRequired {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one number..
        /// </summary>
        internal static string Server_Auth_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one lowercase letter..
        /// </summary>
        internal static string Server_Auth_PasswordRequiresLowercase {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordRequiresLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one special character..
        /// </summary>
        internal static string Server_Auth_PasswordRequiresSpecialCharacter {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordRequiresSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one uppercase letter..
        /// </summary>
        internal static string Server_Auth_PasswordRequiresUppercase {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordRequiresUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password reset data is required..
        /// </summary>
        internal static string Server_Auth_PasswordResetDataRequired {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The recovery code could not be sent..
        /// </summary>
        internal static string Server_Auth_PasswordResetEmailFailed {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The recovery code was sent..
        /// </summary>
        internal static string Server_Auth_PasswordResetEmailSent {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password reset failed..
        /// </summary>
        internal static string Server_Auth_PasswordResetFailed {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password reset request data is required..
        /// </summary>
        internal static string Server_Auth_PasswordResetRequestDataRequired {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetRequestDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If the email is registered, you will receive a recovery code..
        /// </summary>
        internal static string Server_Auth_PasswordResetRequestProcessed {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetRequestProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password reset successfully..
        /// </summary>
        internal static string Server_Auth_PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum number of attempts was exceeded..
        /// </summary>
        internal static string Server_Auth_PasswordResetTokenAttemptsExceeded {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetTokenAttemptsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The recovery code has expired..
        /// </summary>
        internal static string Server_Auth_PasswordResetTokenExpired {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No valid recovery code was found..
        /// </summary>
        internal static string Server_Auth_PasswordResetTokenNotFound {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordResetTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is too long..
        /// </summary>
        internal static string Server_Auth_PasswordTooLong {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is too short..
        /// </summary>
        internal static string Server_Auth_PasswordTooShort {
            get {
                return ResourceManager.GetString("Server_Auth_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number is required..
        /// </summary>
        internal static string Server_Auth_PhoneRequired {
            get {
                return ResourceManager.GetString("Server_Auth_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player profile is not available..
        /// </summary>
        internal static string Server_Auth_PlayerProfileNotAvailable {
            get {
                return ResourceManager.GetString("Server_Auth_PlayerProfileNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration data is required..
        /// </summary>
        internal static string Server_Auth_RegistrationDataRequired {
            get {
                return ResourceManager.GetString("Server_Auth_RegistrationDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code is required..
        /// </summary>
        internal static string Server_Auth_VerificationCodeRequired {
            get {
                return ResourceManager.GetString("Server_Auth_VerificationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification email could not be sent..
        /// </summary>
        internal static string Server_Auth_VerificationEmailResendFailed {
            get {
                return ResourceManager.GetString("Server_Auth_VerificationEmailResendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If the email is registered, you will receive a new verification code..
        /// </summary>
        internal static string Server_Auth_VerificationEmailResendProcessed {
            get {
                return ResourceManager.GetString("Server_Auth_VerificationEmailResendProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A new verification code was sent..
        /// </summary>
        internal static string Server_Auth_VerificationEmailResent {
            get {
                return ResourceManager.GetString("Server_Auth_VerificationEmailResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is a system configuration problem..
        /// </summary>
        internal static string Server_Common_ConfigurationError {
            get {
                return ResourceManager.GetString("Server_Common_ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to the database..
        /// </summary>
        internal static string Server_Common_DatabaseConnectionError {
            get {
                return ResourceManager.GetString("Server_Common_DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The operation could not be completed due to a data restriction..
        /// </summary>
        internal static string Server_Common_DatabaseConstraintError {
            get {
                return ResourceManager.GetString("Server_Common_DatabaseConstraintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A record with that data already exists..
        /// </summary>
        internal static string Server_Common_DatabaseDuplicateKey {
            get {
                return ResourceManager.GetString("Server_Common_DatabaseDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The operation took too long. Please try again..
        /// </summary>
        internal static string Server_Common_DatabaseTimeout {
            get {
                return ResourceManager.GetString("Server_Common_DatabaseTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The database is unavailable..
        /// </summary>
        internal static string Server_Common_DatabaseUnavailable {
            get {
                return ResourceManager.GetString("Server_Common_DatabaseUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred during the operation..
        /// </summary>
        internal static string Server_Common_RuntimeError {
            get {
                return ResourceManager.GetString("Server_Common_RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred..
        /// </summary>
        internal static string Server_Common_UnexpectedError {
            get {
                return ResourceManager.GetString("Server_Common_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account is not available..
        /// </summary>
        internal static string Server_Match_AccountNotAvailable {
            get {
                return ResourceManager.GetString("Server_Match_AccountNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account was not found..
        /// </summary>
        internal static string Server_Match_AccountNotFound {
            get {
                return ResourceManager.GetString("Server_Match_AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available lobbies retrieved successfully..
        /// </summary>
        internal static string Server_Match_AvailableLobbiesRetrieved {
            get {
                return ResourceManager.GetString("Server_Match_AvailableLobbiesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot join your own match..
        /// </summary>
        internal static string Server_Match_CannotJoinOwnMatch {
            get {
                return ResourceManager.GetString("Server_Match_CannotJoinOwnMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must verify your email before continuing..
        /// </summary>
        internal static string Server_Match_EmailVerificationRequired {
            get {
                return ResourceManager.GetString("Server_Match_EmailVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account is not valid..
        /// </summary>
        internal static string Server_Match_InvalidAccountId {
            get {
                return ResourceManager.GetString("Server_Match_InvalidAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected language is not valid..
        /// </summary>
        internal static string Server_Match_InvalidLanguageCode {
            get {
                return ResourceManager.GetString("Server_Match_InvalidLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match is not valid..
        /// </summary>
        internal static string Server_Match_InvalidMatchId {
            get {
                return ResourceManager.GetString("Server_Match_InvalidMatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby created successfully..
        /// </summary>
        internal static string Server_Match_LobbyCreated {
            get {
                return ResourceManager.GetString("Server_Match_LobbyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby creation failed..
        /// </summary>
        internal static string Server_Match_LobbyCreationFailed {
            get {
                return ResourceManager.GetString("Server_Match_LobbyCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You joined the lobby successfully..
        /// </summary>
        internal static string Server_Match_LobbyJoined {
            get {
                return ResourceManager.GetString("Server_Match_LobbyJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not join the lobby..
        /// </summary>
        internal static string Server_Match_LobbyJoinFailed {
            get {
                return ResourceManager.GetString("Server_Match_LobbyJoinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match is no longer available..
        /// </summary>
        internal static string Server_Match_MatchNotAvailable {
            get {
                return ResourceManager.GetString("Server_Match_MatchNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match was not found..
        /// </summary>
        internal static string Server_Match_MatchNotFound {
            get {
                return ResourceManager.GetString("Server_Match_MatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player is already in an active match..
        /// </summary>
        internal static string Server_Match_PlayerAlreadyInActiveMatch {
            get {
                return ResourceManager.GetString("Server_Match_PlayerAlreadyInActiveMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player profile is not available..
        /// </summary>
        internal static string Server_Match_PlayerProfileNotAvailable {
            get {
                return ResourceManager.GetString("Server_Match_PlayerProfileNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account is not available..
        /// </summary>
        internal static string Server_Profile_AccountNotAvailable {
            get {
                return ResourceManager.GetString("Server_Profile_AccountNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account was not found..
        /// </summary>
        internal static string Server_Profile_AccountNotFound {
            get {
                return ResourceManager.GetString("Server_Profile_AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must verify your email before continuing..
        /// </summary>
        internal static string Server_Profile_EmailVerificationRequired {
            get {
                return ResourceManager.GetString("Server_Profile_EmailVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full name is required..
        /// </summary>
        internal static string Server_Profile_FullNameRequired {
            get {
                return ResourceManager.GetString("Server_Profile_FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account is not valid..
        /// </summary>
        internal static string Server_Profile_InvalidAccountId {
            get {
                return ResourceManager.GetString("Server_Profile_InvalidAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth is not valid..
        /// </summary>
        internal static string Server_Profile_InvalidDateOfBirth {
            get {
                return ResourceManager.GetString("Server_Profile_InvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected language is not valid..
        /// </summary>
        internal static string Server_Profile_InvalidPreferredLanguage {
            get {
                return ResourceManager.GetString("Server_Profile_InvalidPreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number is required..
        /// </summary>
        internal static string Server_Profile_PhoneRequired {
            get {
                return ResourceManager.GetString("Server_Profile_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player profile is not available..
        /// </summary>
        internal static string Server_Profile_PlayerProfileNotAvailable {
            get {
                return ResourceManager.GetString("Server_Profile_PlayerProfileNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile data is required..
        /// </summary>
        internal static string Server_Profile_ProfileDataRequired {
            get {
                return ResourceManager.GetString("Server_Profile_ProfileDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile deleted successfully..
        /// </summary>
        internal static string Server_Profile_ProfileDeleted {
            get {
                return ResourceManager.GetString("Server_Profile_ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile deletion failed..
        /// </summary>
        internal static string Server_Profile_ProfileDeleteFailed {
            get {
                return ResourceManager.GetString("Server_Profile_ProfileDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile retrieved successfully..
        /// </summary>
        internal static string Server_Profile_ProfileRetrieved {
            get {
                return ResourceManager.GetString("Server_Profile_ProfileRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile updated successfully..
        /// </summary>
        internal static string Server_Profile_ProfileUpdated {
            get {
                return ResourceManager.GetString("Server_Profile_ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile update failed..
        /// </summary>
        internal static string Server_Profile_ProfileUpdateFailed {
            get {
                return ResourceManager.GetString("Server_Profile_ProfileUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories retrieved successfully..
        /// </summary>
        internal static string Server_Word_CategoriesRetrieved {
            get {
                return ResourceManager.GetString("Server_Word_CategoriesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected language is not valid..
        /// </summary>
        internal static string Server_Word_InvalidLanguageCode {
            get {
                return ResourceManager.GetString("Server_Word_InvalidLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No categories were found..
        /// </summary>
        internal static string Server_Word_NoCategoriesFound {
            get {
                return ResourceManager.GetString("Server_Word_NoCategoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password confirmation is required..
        /// </summary>
        internal static string Validation_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("Validation_ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth cannot be in the future..
        /// </summary>
        internal static string Validation_DateOfBirthInFuture {
            get {
                return ResourceManager.GetString("Validation_DateOfBirthInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth is not valid..
        /// </summary>
        internal static string Validation_DateOfBirthInvalid {
            get {
                return ResourceManager.GetString("Validation_DateOfBirthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth is required..
        /// </summary>
        internal static string Validation_DateOfBirthRequired {
            get {
                return ResourceManager.GetString("Validation_DateOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email format is not valid..
        /// </summary>
        internal static string Validation_EmailInvalidFormat {
            get {
                return ResourceManager.GetString("Validation_EmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is required..
        /// </summary>
        internal static string Validation_EmailRequired {
            get {
                return ResourceManager.GetString("Validation_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is too long..
        /// </summary>
        internal static string Validation_EmailTooLong {
            get {
                return ResourceManager.GetString("Validation_EmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is too short..
        /// </summary>
        internal static string Validation_EmailTooShort {
            get {
                return ResourceManager.GetString("Validation_EmailTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full name is required..
        /// </summary>
        internal static string Validation_FullNameRequired {
            get {
                return ResourceManager.GetString("Validation_FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full name is too long..
        /// </summary>
        internal static string Validation_FullNameTooLong {
            get {
                return ResourceManager.GetString("Validation_FullNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full name is too short..
        /// </summary>
        internal static string Validation_FullNameTooShort {
            get {
                return ResourceManager.GetString("Validation_FullNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login data is required..
        /// </summary>
        internal static string Validation_LoginFormRequired {
            get {
                return ResourceManager.GetString("Validation_LoginFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must not contain spaces..
        /// </summary>
        internal static string Validation_PasswordContainsWhiteSpace {
            get {
                return ResourceManager.GetString("Validation_PasswordContainsWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required..
        /// </summary>
        internal static string Validation_PasswordRequired {
            get {
                return ResourceManager.GetString("Validation_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one number..
        /// </summary>
        internal static string Validation_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("Validation_PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one lowercase letter..
        /// </summary>
        internal static string Validation_PasswordRequiresLowercase {
            get {
                return ResourceManager.GetString("Validation_PasswordRequiresLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one special character..
        /// </summary>
        internal static string Validation_PasswordRequiresSpecialCharacter {
            get {
                return ResourceManager.GetString("Validation_PasswordRequiresSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one uppercase letter..
        /// </summary>
        internal static string Validation_PasswordRequiresUppercase {
            get {
                return ResourceManager.GetString("Validation_PasswordRequiresUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match..
        /// </summary>
        internal static string Validation_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is too long..
        /// </summary>
        internal static string Validation_PasswordTooLong {
            get {
                return ResourceManager.GetString("Validation_PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must have at least 8 characters..
        /// </summary>
        internal static string Validation_PasswordTooShort {
            get {
                return ResourceManager.GetString("Validation_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number format is not valid..
        /// </summary>
        internal static string Validation_PhoneInvalidFormat {
            get {
                return ResourceManager.GetString("Validation_PhoneInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number is required..
        /// </summary>
        internal static string Validation_PhoneRequired {
            get {
                return ResourceManager.GetString("Validation_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number is too long..
        /// </summary>
        internal static string Validation_PhoneTooLong {
            get {
                return ResourceManager.GetString("Validation_PhoneTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number is too short..
        /// </summary>
        internal static string Validation_PhoneTooShort {
            get {
                return ResourceManager.GetString("Validation_PhoneTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected language is not available..
        /// </summary>
        internal static string Validation_PreferredLanguageNotAvailable {
            get {
                return ResourceManager.GetString("Validation_PreferredLanguageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferred language is required..
        /// </summary>
        internal static string Validation_PreferredLanguageRequired {
            get {
                return ResourceManager.GetString("Validation_PreferredLanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language code is too long..
        /// </summary>
        internal static string Validation_PreferredLanguageTooLong {
            get {
                return ResourceManager.GetString("Validation_PreferredLanguageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language code is too short..
        /// </summary>
        internal static string Validation_PreferredLanguageTooShort {
            get {
                return ResourceManager.GetString("Validation_PreferredLanguageTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration data is required..
        /// </summary>
        internal static string Validation_RegisterFormRequired {
            get {
                return ResourceManager.GetString("Validation_RegisterFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code must contain only numbers..
        /// </summary>
        internal static string Validation_VerificationCodeInvalidFormat {
            get {
                return ResourceManager.GetString("Validation_VerificationCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code must have 6 digits..
        /// </summary>
        internal static string Validation_VerificationCodeInvalidLength {
            get {
                return ResourceManager.GetString("Validation_VerificationCodeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code is required..
        /// </summary>
        internal static string Validation_VerificationCodeRequired {
            get {
                return ResourceManager.GetString("Validation_VerificationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification data is required..
        /// </summary>
        internal static string Validation_VerifyEmailFormRequired {
            get {
                return ResourceManager.GetString("Validation_VerifyEmailFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to sign in.
        /// </summary>
        internal static string VerifyEmail_BackToLogin {
            get {
                return ResourceManager.GetString("VerifyEmail_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VERIFY.
        /// </summary>
        internal static string VerifyEmail_Button {
            get {
                return ResourceManager.GetString("VerifyEmail_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        internal static string VerifyEmail_CodeLabel {
            get {
                return ResourceManager.GetString("VerifyEmail_CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the 6-digit code.
        /// </summary>
        internal static string VerifyEmail_CodeTooltip {
            get {
                return ResourceManager.GetString("VerifyEmail_CodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code that was sent to your email..
        /// </summary>
        internal static string VerifyEmail_Description {
            get {
                return ResourceManager.GetString("VerifyEmail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string VerifyEmail_EmailLabel {
            get {
                return ResourceManager.GetString("VerifyEmail_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESEND CODE.
        /// </summary>
        internal static string VerifyEmail_ResendCodeButton {
            get {
                return ResourceManager.GetString("VerifyEmail_ResendCodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VERIFY ACCOUNT.
        /// </summary>
        internal static string VerifyEmail_Title {
            get {
                return ResourceManager.GetString("VerifyEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hangman - Account verification.
        /// </summary>
        internal static string VerifyEmail_WindowTitle {
            get {
                return ResourceManager.GetString("VerifyEmail_WindowTitle", resourceCulture);
            }
        }
    }
}
