//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.ServiceReferenceWord {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWord.IWordService")]
    public interface IWordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetCategoriesByLanguage", ReplyAction="http://tempuri.org/IWordService/GetCategoriesByLanguageResponse")]
        Hangman.Contracts.Word.GetCategoriesByLanguageResponse GetCategoriesByLanguage(Hangman.Contracts.Word.GetCategoriesByLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetCategoriesByLanguage", ReplyAction="http://tempuri.org/IWordService/GetCategoriesByLanguageResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Word.GetCategoriesByLanguageResponse> GetCategoriesByLanguageAsync(Hangman.Contracts.Word.GetCategoriesByLanguageRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordServiceChannel : Hangman.Client.ServiceReferenceWord.IWordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordServiceClient : System.ServiceModel.ClientBase<Hangman.Client.ServiceReferenceWord.IWordService>, Hangman.Client.ServiceReferenceWord.IWordService {
        
        public WordServiceClient() {
        }
        
        public WordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hangman.Contracts.Word.GetCategoriesByLanguageResponse GetCategoriesByLanguage(Hangman.Contracts.Word.GetCategoriesByLanguageRequest request) {
            return base.Channel.GetCategoriesByLanguage(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Word.GetCategoriesByLanguageResponse> GetCategoriesByLanguageAsync(Hangman.Contracts.Word.GetCategoriesByLanguageRequest request) {
            return base.Channel.GetCategoriesByLanguageAsync(request);
        }
    }
}
