//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.ServiceReferenceProfile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProfile.IProfileService")]
    public interface IProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/GetProfile", ReplyAction="http://tempuri.org/IProfileService/GetProfileResponse")]
        Hangman.Contracts.Profile.GetProfileResponse GetProfile(Hangman.Contracts.Profile.GetProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/GetProfile", ReplyAction="http://tempuri.org/IProfileService/GetProfileResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Profile.GetProfileResponse> GetProfileAsync(Hangman.Contracts.Profile.GetProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/UpdateProfile", ReplyAction="http://tempuri.org/IProfileService/UpdateProfileResponse")]
        Hangman.Contracts.Profile.UpdateProfileResponse UpdateProfile(Hangman.Contracts.Profile.UpdateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/UpdateProfile", ReplyAction="http://tempuri.org/IProfileService/UpdateProfileResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Profile.UpdateProfileResponse> UpdateProfileAsync(Hangman.Contracts.Profile.UpdateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/DeleteProfile", ReplyAction="http://tempuri.org/IProfileService/DeleteProfileResponse")]
        Hangman.Contracts.Profile.DeleteProfileResponse DeleteProfile(Hangman.Contracts.Profile.DeleteProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/DeleteProfile", ReplyAction="http://tempuri.org/IProfileService/DeleteProfileResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Profile.DeleteProfileResponse> DeleteProfileAsync(Hangman.Contracts.Profile.DeleteProfileRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceChannel : Hangman.Client.ServiceReferenceProfile.IProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<Hangman.Client.ServiceReferenceProfile.IProfileService>, Hangman.Client.ServiceReferenceProfile.IProfileService {
        
        public ProfileServiceClient() {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hangman.Contracts.Profile.GetProfileResponse GetProfile(Hangman.Contracts.Profile.GetProfileRequest request) {
            return base.Channel.GetProfile(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Profile.GetProfileResponse> GetProfileAsync(Hangman.Contracts.Profile.GetProfileRequest request) {
            return base.Channel.GetProfileAsync(request);
        }
        
        public Hangman.Contracts.Profile.UpdateProfileResponse UpdateProfile(Hangman.Contracts.Profile.UpdateProfileRequest request) {
            return base.Channel.UpdateProfile(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Profile.UpdateProfileResponse> UpdateProfileAsync(Hangman.Contracts.Profile.UpdateProfileRequest request) {
            return base.Channel.UpdateProfileAsync(request);
        }
        
        public Hangman.Contracts.Profile.DeleteProfileResponse DeleteProfile(Hangman.Contracts.Profile.DeleteProfileRequest request) {
            return base.Channel.DeleteProfile(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Profile.DeleteProfileResponse> DeleteProfileAsync(Hangman.Contracts.Profile.DeleteProfileRequest request) {
            return base.Channel.DeleteProfileAsync(request);
        }
    }
}
