//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.ServiceReferenceChat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceChat.IMatchChatService")]
    public interface IMatchChatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchChatService/SendMessage", ReplyAction="http://tempuri.org/IMatchChatService/SendMessageResponse")]
        Hangman.Contracts.Match.SendMatchChatMessageResponse SendMessage(Hangman.Contracts.Match.SendMatchChatMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchChatService/SendMessage", ReplyAction="http://tempuri.org/IMatchChatService/SendMessageResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.SendMatchChatMessageResponse> SendMessageAsync(Hangman.Contracts.Match.SendMatchChatMessageRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchChatServiceChannel : Hangman.Client.ServiceReferenceChat.IMatchChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchChatServiceClient : System.ServiceModel.ClientBase<Hangman.Client.ServiceReferenceChat.IMatchChatService>, Hangman.Client.ServiceReferenceChat.IMatchChatService {
        
        public MatchChatServiceClient() {
        }
        
        public MatchChatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchChatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchChatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchChatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hangman.Contracts.Match.SendMatchChatMessageResponse SendMessage(Hangman.Contracts.Match.SendMatchChatMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.SendMatchChatMessageResponse> SendMessageAsync(Hangman.Contracts.Match.SendMatchChatMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
    }
}
