//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Client.ServiceReferenceMatchGuess {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMatchGuess.IMatchGuessService")]
    public interface IMatchGuessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGuessService/GetGameState", ReplyAction="http://tempuri.org/IMatchGuessService/GetGameStateResponse")]
        Hangman.Contracts.Match.GetMatchGameStateResponse GetGameState(Hangman.Contracts.Match.GetMatchGameStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGuessService/GetGameState", ReplyAction="http://tempuri.org/IMatchGuessService/GetGameStateResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.GetMatchGameStateResponse> GetGameStateAsync(Hangman.Contracts.Match.GetMatchGameStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGuessService/GuessLetter", ReplyAction="http://tempuri.org/IMatchGuessService/GuessLetterResponse")]
        Hangman.Contracts.Match.GuessLetterResponse GuessLetter(Hangman.Contracts.Match.GuessLetterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGuessService/GuessLetter", ReplyAction="http://tempuri.org/IMatchGuessService/GuessLetterResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.GuessLetterResponse> GuessLetterAsync(Hangman.Contracts.Match.GuessLetterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGuessService/GuessWord", ReplyAction="http://tempuri.org/IMatchGuessService/GuessWordResponse")]
        Hangman.Contracts.Match.GuessWordResponse GuessWord(Hangman.Contracts.Match.GuessWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGuessService/GuessWord", ReplyAction="http://tempuri.org/IMatchGuessService/GuessWordResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.GuessWordResponse> GuessWordAsync(Hangman.Contracts.Match.GuessWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGuessService/ResolveGuessTimeout", ReplyAction="http://tempuri.org/IMatchGuessService/ResolveGuessTimeoutResponse")]
        Hangman.Contracts.Match.ResolveGuessTimeoutResponse ResolveGuessTimeout(Hangman.Contracts.Match.ResolveGuessTimeoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGuessService/ResolveGuessTimeout", ReplyAction="http://tempuri.org/IMatchGuessService/ResolveGuessTimeoutResponse")]
        System.Threading.Tasks.Task<Hangman.Contracts.Match.ResolveGuessTimeoutResponse> ResolveGuessTimeoutAsync(Hangman.Contracts.Match.ResolveGuessTimeoutRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchGuessServiceChannel : Hangman.Client.ServiceReferenceMatchGuess.IMatchGuessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchGuessServiceClient : System.ServiceModel.ClientBase<Hangman.Client.ServiceReferenceMatchGuess.IMatchGuessService>, Hangman.Client.ServiceReferenceMatchGuess.IMatchGuessService {
        
        public MatchGuessServiceClient() {
        }
        
        public MatchGuessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchGuessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchGuessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchGuessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hangman.Contracts.Match.GetMatchGameStateResponse GetGameState(Hangman.Contracts.Match.GetMatchGameStateRequest request) {
            return base.Channel.GetGameState(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.GetMatchGameStateResponse> GetGameStateAsync(Hangman.Contracts.Match.GetMatchGameStateRequest request) {
            return base.Channel.GetGameStateAsync(request);
        }
        
        public Hangman.Contracts.Match.GuessLetterResponse GuessLetter(Hangman.Contracts.Match.GuessLetterRequest request) {
            return base.Channel.GuessLetter(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.GuessLetterResponse> GuessLetterAsync(Hangman.Contracts.Match.GuessLetterRequest request) {
            return base.Channel.GuessLetterAsync(request);
        }
        
        public Hangman.Contracts.Match.GuessWordResponse GuessWord(Hangman.Contracts.Match.GuessWordRequest request) {
            return base.Channel.GuessWord(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.GuessWordResponse> GuessWordAsync(Hangman.Contracts.Match.GuessWordRequest request) {
            return base.Channel.GuessWordAsync(request);
        }
        
        public Hangman.Contracts.Match.ResolveGuessTimeoutResponse ResolveGuessTimeout(Hangman.Contracts.Match.ResolveGuessTimeoutRequest request) {
            return base.Channel.ResolveGuessTimeout(request);
        }
        
        public System.Threading.Tasks.Task<Hangman.Contracts.Match.ResolveGuessTimeoutResponse> ResolveGuessTimeoutAsync(Hangman.Contracts.Match.ResolveGuessTimeoutRequest request) {
            return base.Channel.ResolveGuessTimeoutAsync(request);
        }
    }
}
